// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartMeal.Data;

#nullable disable

namespace SmartMeal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523110506_SeedDishRelations")]
    partial class SeedDishRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartMeal.Models.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Молочные продукты и лактоза.",
                            Name = "Молоко"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Орехи и продукты, которые могут содержать следы орехов.",
                            Name = "Орехи"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Апельсины, лимоны, мандарины и другие цитрусовые.",
                            Name = "Цитрусовые"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Пшеница, рожь, ячмень и продукты с глютеном.",
                            Name = "Глютен"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Куриные яйца и продукты с их содержанием.",
                            Name = "Яйца"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Рыба и рыбные продукты.",
                            Name = "Рыба"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Креветки, мидии, кальмары и другие морепродукты.",
                            Name = "Морепродукты"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Соя и соевые продукты.",
                            Name = "Соя"
                        });
                });

            modelBuilder.Entity("SmartMeal.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Завтрак",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Обед",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ужин",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Перекус",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("SmartMeal.Models.DietType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DietTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Рацион с повышенным содержанием белка.",
                            Name = "Высокобелковая"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Рацион без продуктов, содержащих глютен.",
                            Name = "Без глютена"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Рацион без мясных продуктов.",
                            Name = "Вегетарианская"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Рацион с низким содержанием углеводов и высоким содержанием жиров.",
                            Name = "Кето"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Рацион с пониженной калорийностью.",
                            Name = "Низкокалорийная"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Рацион с ограничением углеводов.",
                            Name = "Низкоуглеводная"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Сбалансированный рацион для здорового питания.",
                            Name = "Правильное питание"
                        });
                });

            modelBuilder.Entity("SmartMeal.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Calories")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Carbs")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CookingTime")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByUserProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fats")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("IngredientsList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForChildren")
                        .HasColumnType("bit");

                    b.Property<string>("MainIngredient")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Proteins")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserProfileId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 310m,
                            Carbs = 54m,
                            CategoryId = 1,
                            CookingTime = 15,
                            Description = "Теплая овсяная каша на завтрак с кусочками яблока и корицей.",
                            Fats = 7m,
                            IngredientsList = "Овсяные хлопья, молоко, яблоко, корица, мед",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Овсяные хлопья",
                            Name = "Овсяная каша с яблоком",
                            Proteins = 9m
                        },
                        new
                        {
                            Id = 2,
                            Calories = 360m,
                            Carbs = 34m,
                            CategoryId = 1,
                            CookingTime = 45,
                            Description = "Нежная запеканка из творога с легкой сладостью и мягкой текстурой.",
                            Fats = 14m,
                            IngredientsList = "Творог, яйцо, манная крупа, сметана, сахар",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Творог",
                            Name = "Творожная запеканка",
                            Proteins = 24m
                        },
                        new
                        {
                            Id = 3,
                            Calories = 280m,
                            Carbs = 30m,
                            CategoryId = 2,
                            CookingTime = 50,
                            Description = "Легкий обеденный суп с курицей, картофелем, морковью и зеленью.",
                            Fats = 8m,
                            IngredientsList = "Куриное филе, картофель, морковь, лук, зелень",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Курица",
                            Name = "Куриный суп с овощами",
                            Proteins = 22m
                        },
                        new
                        {
                            Id = 4,
                            Calories = 470m,
                            Carbs = 55m,
                            CategoryId = 2,
                            CookingTime = 40,
                            Description = "Сытное блюдо для обеда из рассыпчатой гречки и тушеной индейки.",
                            Fats = 12m,
                            IngredientsList = "Гречневая крупа, филе индейки, морковь, лук, растительное масло",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Индейка",
                            Name = "Гречка с индейкой",
                            Proteins = 35m
                        },
                        new
                        {
                            Id = 5,
                            Calories = 390m,
                            Carbs = 25m,
                            CategoryId = 3,
                            CookingTime = 35,
                            Description = "Ужин из белой рыбы, запеченной с кабачком, перцем и томатами.",
                            Fats = 16m,
                            IngredientsList = "Белая рыба, кабачок, болгарский перец, томаты, лимонный сок",
                            IsCustom = false,
                            IsForChildren = false,
                            MainIngredient = "Рыба",
                            Name = "Запеченная рыба с овощами",
                            Proteins = 32m
                        },
                        new
                        {
                            Id = 6,
                            Calories = 340m,
                            Carbs = 48m,
                            CategoryId = 3,
                            CookingTime = 45,
                            Description = "Питательное овощное рагу с фасолью, томатами и ароматными специями.",
                            Fats = 9m,
                            IngredientsList = "Фасоль, картофель, морковь, томаты, лук, специи",
                            IsCustom = false,
                            IsForChildren = false,
                            MainIngredient = "Фасоль",
                            Name = "Овощное рагу с фасолью",
                            Proteins = 15m
                        },
                        new
                        {
                            Id = 7,
                            Calories = 190m,
                            Carbs = 26m,
                            CategoryId = 4,
                            CookingTime = 5,
                            Description = "Быстрый перекус из натурального йогурта со свежими ягодами.",
                            Fats = 5m,
                            IngredientsList = "Натуральный йогурт, ягоды, овсяные хлопья",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Йогурт",
                            Name = "Йогурт с ягодами",
                            Proteins = 10m
                        },
                        new
                        {
                            Id = 8,
                            Calories = 330m,
                            Carbs = 35m,
                            CategoryId = 4,
                            CookingTime = 10,
                            Description = "Простой перекус с куриным филе, овощами и цельнозерновым хлебом.",
                            Fats = 10m,
                            IngredientsList = "Цельнозерновой хлеб, куриное филе, огурец, лист салата, йогуртовый соус",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Курица",
                            Name = "Сэндвич с курицей",
                            Proteins = 24m
                        });
                });

            modelBuilder.Entity("SmartMeal.Models.DishAllergen", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("AllergenId")
                        .HasColumnType("int");

                    b.HasKey("DishId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("DishAllergens");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            AllergenId = 1
                        },
                        new
                        {
                            DishId = 1,
                            AllergenId = 4
                        },
                        new
                        {
                            DishId = 2,
                            AllergenId = 1
                        },
                        new
                        {
                            DishId = 2,
                            AllergenId = 5
                        },
                        new
                        {
                            DishId = 2,
                            AllergenId = 4
                        },
                        new
                        {
                            DishId = 5,
                            AllergenId = 6
                        },
                        new
                        {
                            DishId = 5,
                            AllergenId = 3
                        },
                        new
                        {
                            DishId = 7,
                            AllergenId = 1
                        },
                        new
                        {
                            DishId = 8,
                            AllergenId = 4
                        },
                        new
                        {
                            DishId = 8,
                            AllergenId = 1
                        });
                });

            modelBuilder.Entity("SmartMeal.Models.DishDietType", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("DietTypeId")
                        .HasColumnType("int");

                    b.HasKey("DishId", "DietTypeId");

                    b.HasIndex("DietTypeId");

                    b.ToTable("DishDietTypes");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            DietTypeId = 5
                        },
                        new
                        {
                            DishId = 1,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 2,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 2,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 3,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 3,
                            DietTypeId = 5
                        },
                        new
                        {
                            DishId = 3,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 4,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 4,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 5,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 5,
                            DietTypeId = 6
                        },
                        new
                        {
                            DishId = 5,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 6,
                            DietTypeId = 3
                        },
                        new
                        {
                            DishId = 6,
                            DietTypeId = 5
                        },
                        new
                        {
                            DishId = 6,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 7,
                            DietTypeId = 5
                        },
                        new
                        {
                            DishId = 7,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 8,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 8,
                            DietTypeId = 7
                        });
                });

            modelBuilder.Entity("SmartMeal.Models.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("SmartMeal.Models.UserAllergen", b =>
                {
                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int>("AllergenId")
                        .HasColumnType("int");

                    b.HasKey("UserProfileId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("UserAllergens");
                });

            modelBuilder.Entity("SmartMeal.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal>("DailyCalories")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Goal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Height")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("SmartMeal.Models.Dish", b =>
                {
                    b.HasOne("SmartMeal.Models.Category", "Category")
                        .WithMany("Dishes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Models.UserProfile", "CreatedByUserProfile")
                        .WithMany("CustomDishes")
                        .HasForeignKey("CreatedByUserProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("CreatedByUserProfile");
                });

            modelBuilder.Entity("SmartMeal.Models.DishAllergen", b =>
                {
                    b.HasOne("SmartMeal.Models.Allergen", "Allergen")
                        .WithMany("DishAllergens")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Models.Dish", "Dish")
                        .WithMany("DishAllergens")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("SmartMeal.Models.DishDietType", b =>
                {
                    b.HasOne("SmartMeal.Models.DietType", "DietType")
                        .WithMany("DishDietTypes")
                        .HasForeignKey("DietTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Models.Dish", "Dish")
                        .WithMany("DishDietTypes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietType");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("SmartMeal.Models.MealPlan", b =>
                {
                    b.HasOne("SmartMeal.Models.Dish", "Dish")
                        .WithMany("MealPlans")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Models.UserProfile", "UserProfile")
                        .WithMany("MealPlans")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SmartMeal.Models.UserAllergen", b =>
                {
                    b.HasOne("SmartMeal.Models.Allergen", "Allergen")
                        .WithMany("UserAllergens")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Models.UserProfile", "UserProfile")
                        .WithMany("UserAllergens")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SmartMeal.Models.Allergen", b =>
                {
                    b.Navigation("DishAllergens");

                    b.Navigation("UserAllergens");
                });

            modelBuilder.Entity("SmartMeal.Models.Category", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("SmartMeal.Models.DietType", b =>
                {
                    b.Navigation("DishDietTypes");
                });

            modelBuilder.Entity("SmartMeal.Models.Dish", b =>
                {
                    b.Navigation("DishAllergens");

                    b.Navigation("DishDietTypes");

                    b.Navigation("MealPlans");
                });

            modelBuilder.Entity("SmartMeal.Models.UserProfile", b =>
                {
                    b.Navigation("CustomDishes");

                    b.Navigation("MealPlans");

                    b.Navigation("UserAllergens");
                });
#pragma warning restore 612, 618
        }
    }
}
