// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartMeal.Data;

#nullable disable

namespace SmartMeal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260531120948_AddFirstSeedRecipeImages")]
    partial class AddFirstSeedRecipeImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartMeal.Models.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Молочные продукты и лактоза.",
                            Name = "Молоко"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Орехи и продукты, которые могут содержать следы орехов.",
                            Name = "Орехи"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Апельсины, лимоны, мандарины и другие цитрусовые.",
                            Name = "Цитрусовые"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Пшеница, рожь, ячмень и продукты с глютеном.",
                            Name = "Глютен"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Куриные яйца и продукты с их содержанием.",
                            Name = "Яйца"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Рыба и рыбные продукты.",
                            Name = "Рыба"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Креветки, мидии, кальмары и другие морепродукты.",
                            Name = "Морепродукты"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Соя и соевые продукты.",
                            Name = "Соя"
                        });
                });

            modelBuilder.Entity("SmartMeal.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Завтрак",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Обед",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ужин",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Перекус",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("SmartMeal.Models.DietType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DietTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Рацион с повышенным содержанием белка.",
                            Name = "Высокобелковая"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Рацион без продуктов, содержащих глютен.",
                            Name = "Без глютена"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Рацион без мясных продуктов.",
                            Name = "Вегетарианская"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Рацион с низким содержанием углеводов и высоким содержанием жиров.",
                            Name = "Кето"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Рацион с пониженной калорийностью.",
                            Name = "Низкокалорийная"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Рацион с ограничением углеводов.",
                            Name = "Низкоуглеводная"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Сбалансированный рацион для здорового питания.",
                            Name = "Правильное питание"
                        });
                });

            modelBuilder.Entity("SmartMeal.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Calories")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Carbs")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CookingTime")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByUserProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fats")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("IngredientsList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForChildren")
                        .HasColumnType("bit");

                    b.Property<string>("MainIngredient")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Proteins")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserProfileId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 310m,
                            Carbs = 54m,
                            CategoryId = 1,
                            CookingTime = 15,
                            Description = "1. Сварите овсяные хлопья на молоке с щепоткой соли. 2. Добавьте нарезанное яблоко, корицу и мед. 3. Прогрейте 2 минуты и подавайте теплой.",
                            Fats = 7m,
                            ImageUrl = "/images/dishes/seeded/oatmeal-with-apple.png",
                            IngredientsList = "Овсяные хлопья 50 г, молоко 2,5% 180 мл, яблоко 100 г, мед 8 г, корица 1 г, соль 1 г",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Овсяные хлопья",
                            Name = "Овсяная каша с яблоком",
                            Proteins = 9m
                        },
                        new
                        {
                            Id = 2,
                            Calories = 360m,
                            Carbs = 34m,
                            CategoryId = 1,
                            CookingTime = 45,
                            Description = "1. Смешайте творог, яйцо, манку, сметану и сахар. 2. Переложите массу в форму. 3. Запекайте при 180 градусах около 35 минут.",
                            Fats = 14m,
                            ImageUrl = "/images/dishes/breakfast.svg",
                            IngredientsList = "Творог 5% 180 г, яйцо 1 шт., манная крупа 20 г, сметана 10% 25 г, сахар 12 г, ванилин 1 г, соль 1 г",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Творог",
                            Name = "Творожная запеканка",
                            Proteins = 24m
                        },
                        new
                        {
                            Id = 3,
                            Calories = 280m,
                            Carbs = 30m,
                            CategoryId = 2,
                            CookingTime = 50,
                            Description = "1. Отварите куриное филе до готовности. 2. Добавьте картофель, морковь и лук. 3. Варите до мягкости овощей, посолите и посыпьте зеленью.",
                            Fats = 8m,
                            ImageUrl = "/images/dishes/seeded/chicken-vegetable-soup.png",
                            IngredientsList = "Куриное филе 100 г, картофель 120 г, морковь 50 г, лук 35 г, зелень 5 г, соль 2 г, лавровый лист 1 шт.",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Курица",
                            Name = "Куриный суп с овощами",
                            Proteins = 22m
                        },
                        new
                        {
                            Id = 4,
                            Calories = 470m,
                            Carbs = 55m,
                            CategoryId = 2,
                            CookingTime = 40,
                            Description = "1. Отварите гречку до рассыпчатости. 2. Потушите индейку с луком и морковью на масле. 3. Соедините с крупой и прогрейте под крышкой.",
                            Fats = 12m,
                            ImageUrl = "/images/dishes/lunch.svg",
                            IngredientsList = "Гречневая крупа 70 г, филе индейки 130 г, морковь 50 г, лук 40 г, растительное масло 8 г, соль 2 г, черный перец 1 г",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Индейка",
                            Name = "Гречка с индейкой",
                            Proteins = 35m
                        },
                        new
                        {
                            Id = 5,
                            Calories = 390m,
                            Carbs = 25m,
                            CategoryId = 3,
                            CookingTime = 35,
                            Description = "1. Выложите рыбу в форму и сбрызните лимонным соком. 2. Добавьте кабачок, перец и томаты. 3. Запекайте при 190 градусах 25 минут.",
                            Fats = 16m,
                            ImageUrl = "/images/dishes/seeded/baked-fish-with-vegetables.png",
                            IngredientsList = "Филе белой рыбы 160 г, кабачок 120 г, болгарский перец 80 г, томаты 100 г, оливковое масло 10 г, лимонный сок 10 мл, соль 2 г, укроп 5 г",
                            IsCustom = false,
                            IsForChildren = false,
                            MainIngredient = "Рыба",
                            Name = "Запеченная рыба с овощами",
                            Proteins = 32m
                        },
                        new
                        {
                            Id = 6,
                            Calories = 340m,
                            Carbs = 48m,
                            CategoryId = 3,
                            CookingTime = 45,
                            Description = "1. Обжарьте лук и морковь на масле. 2. Добавьте картофель, томаты, фасоль и специи. 3. Тушите до мягкости овощей.",
                            Fats = 9m,
                            ImageUrl = "/images/dishes/dinner.svg",
                            IngredientsList = "Фасоль отварная 120 г, картофель 100 г, морковь 60 г, томаты 120 г, лук 40 г, растительное масло 8 г, соль 2 г, паприка 2 г",
                            IsCustom = false,
                            IsForChildren = false,
                            MainIngredient = "Фасоль",
                            Name = "Овощное рагу с фасолью",
                            Proteins = 15m
                        },
                        new
                        {
                            Id = 7,
                            Calories = 190m,
                            Carbs = 26m,
                            CategoryId = 4,
                            CookingTime = 5,
                            Description = "1. Выложите натуральный йогурт в чашку. 2. Добавьте ягоды и овсяные хлопья. 3. Перемешайте и подавайте сразу.",
                            Fats = 5m,
                            ImageUrl = "/images/dishes/seeded/yogurt-with-berries.png",
                            IngredientsList = "Натуральный йогурт 2,5% 150 г, ягоды 80 г, овсяные хлопья 15 г, мед 5 г",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Йогурт",
                            Name = "Йогурт с ягодами",
                            Proteins = 10m
                        },
                        new
                        {
                            Id = 8,
                            Calories = 330m,
                            Carbs = 35m,
                            CategoryId = 4,
                            CookingTime = 10,
                            Description = "1. Подсушите хлеб. 2. Выложите курицу, огурец, салат и йогуртовый соус. 3. Накройте вторым ломтиком и разрежьте пополам.",
                            Fats = 10m,
                            ImageUrl = "/images/dishes/snack.svg",
                            IngredientsList = "Цельнозерновой хлеб 70 г, куриное филе готовое 80 г, огурец 50 г, лист салата 10 г, йогурт 25 г, горчица 3 г, соль 1 г",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Курица",
                            Name = "Сэндвич с курицей",
                            Proteins = 24m
                        },
                        new
                        {
                            Id = 9,
                            Calories = 330m,
                            Carbs = 5m,
                            CategoryId = 1,
                            CookingTime = 12,
                            Description = "1. Взбейте яйца с молоком и солью. 2. Прогрейте шпинат на сковороде с маслом. 3. Залейте яйцами, посыпьте сыром и готовьте под крышкой.",
                            Fats = 24m,
                            ImageUrl = "/images/dishes/breakfast.svg",
                            IngredientsList = "Яйца 2 шт., молоко 40 мл, шпинат 60 г, твердый сыр 25 г, сливочное масло 5 г, соль 1 г, черный перец 1 г",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Яйца",
                            Name = "Омлет со шпинатом и сыром",
                            Proteins = 24m
                        },
                        new
                        {
                            Id = 10,
                            Calories = 290m,
                            Carbs = 23m,
                            CategoryId = 1,
                            CookingTime = 5,
                            Description = "1. Переложите йогурт в миску. 2. Добавьте орехи, ягоды и мед. 3. Посыпьте семенами чиа и подавайте охлажденным.",
                            Fats = 14m,
                            ImageUrl = "/images/dishes/breakfast.svg",
                            IngredientsList = "Греческий йогурт 170 г, грецкие орехи 15 г, ягоды 60 г, мед 8 г, семена чиа 5 г",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Греческий йогурт",
                            Name = "Греческий йогурт с орехами",
                            Proteins = 20m
                        },
                        new
                        {
                            Id = 11,
                            Calories = 340m,
                            Carbs = 30m,
                            CategoryId = 1,
                            CookingTime = 25,
                            Description = "1. Смешайте творог, яйцо, рисовую муку и немного сахара. 2. Сформируйте сырники. 3. Обжарьте на минимуме масла до румяной корочки.",
                            Fats = 13m,
                            ImageUrl = "/images/dishes/breakfast.svg",
                            IngredientsList = "Творог 5% 180 г, яйцо 1 шт., рисовая мука 25 г, сахар 8 г, растительное масло 5 г, соль 1 г",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Творог",
                            Name = "Сырники из рисовой муки",
                            Proteins = 25m
                        },
                        new
                        {
                            Id = 12,
                            Calories = 360m,
                            Carbs = 9m,
                            CategoryId = 1,
                            CookingTime = 20,
                            Description = "1. Разрежьте авокадо и выньте часть мякоти. 2. Вбейте яйцо, добавьте томаты и специи. 3. Запекайте при 180 градусах до готовности яйца.",
                            Fats = 31m,
                            ImageUrl = "/images/dishes/breakfast.svg",
                            IngredientsList = "Авокадо 120 г, яйцо 1 шт., томаты черри 70 г, оливковое масло 5 г, соль 1 г, черный перец 1 г, зелень 5 г",
                            IsCustom = false,
                            IsForChildren = false,
                            MainIngredient = "Авокадо",
                            Name = "Авокадо с яйцом и томатами",
                            Proteins = 14m
                        },
                        new
                        {
                            Id = 13,
                            Calories = 300m,
                            Carbs = 52m,
                            CategoryId = 1,
                            CookingTime = 30,
                            Description = "1. Нарежьте тыкву кубиками и потушите с водой. 2. Добавьте рис, молоко и соль. 3. Варите до мягкости, затем добавьте масло.",
                            Fats = 7m,
                            ImageUrl = "/images/dishes/breakfast.svg",
                            IngredientsList = "Рис 50 г, тыква 120 г, молоко 180 мл, сливочное масло 5 г, сахар 8 г, соль 1 г",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Тыква",
                            Name = "Рисовая каша с тыквой",
                            Proteins = 8m
                        },
                        new
                        {
                            Id = 14,
                            Calories = 510m,
                            Carbs = 58m,
                            CategoryId = 2,
                            CookingTime = 35,
                            Description = "1. Обжарьте курицу с луком на масле. 2. Добавьте булгур, морковь, перец и воду. 3. Тушите под крышкой до готовности крупы.",
                            Fats = 13m,
                            ImageUrl = "/images/dishes/lunch.svg",
                            IngredientsList = "Булгур 75 г, куриное филе 140 г, морковь 50 г, болгарский перец 70 г, лук 35 г, оливковое масло 8 г, соль 2 г, паприка 2 г",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Курица",
                            Name = "Булгур с курицей и овощами",
                            Proteins = 38m
                        },
                        new
                        {
                            Id = 15,
                            Calories = 320m,
                            Carbs = 46m,
                            CategoryId = 2,
                            CookingTime = 35,
                            Description = "1. Промойте чечевицу. 2. Варите ее с томатами, морковью и луком. 3. Добавьте специи, пробейте часть супа блендером и подавайте.",
                            Fats = 7m,
                            ImageUrl = "/images/dishes/lunch.svg",
                            IngredientsList = "Красная чечевица 70 г, томаты 150 г, морковь 60 г, лук 40 г, оливковое масло 6 г, соль 2 г, зира 1 г, зелень 5 г",
                            IsCustom = false,
                            IsForChildren = false,
                            MainIngredient = "Чечевица",
                            Name = "Чечевичный суп с томатами",
                            Proteins = 18m
                        },
                        new
                        {
                            Id = 16,
                            Calories = 520m,
                            Carbs = 62m,
                            CategoryId = 2,
                            CookingTime = 25,
                            Description = "1. Отварите пасту до готовности. 2. Прогрейте томаты с тунцом и чесноком. 3. Соедините пасту с соусом и посыпьте зеленью.",
                            Fats = 14m,
                            ImageUrl = "/images/dishes/lunch.svg",
                            IngredientsList = "Паста из твердых сортов 80 г, тунец консервированный 100 г, томаты 150 г, оливковое масло 8 г, чеснок 5 г, соль 2 г, базилик 2 г",
                            IsCustom = false,
                            IsForChildren = false,
                            MainIngredient = "Тунец",
                            Name = "Паста с тунцом и томатами",
                            Proteins = 34m
                        },
                        new
                        {
                            Id = 17,
                            Calories = 460m,
                            Carbs = 58m,
                            CategoryId = 2,
                            CookingTime = 30,
                            Description = "1. Отварите киноа. 2. Добавьте нут, огурец, томаты и зелень. 3. Заправьте маслом, лимонным соком и специями.",
                            Fats = 16m,
                            ImageUrl = "/images/dishes/lunch.svg",
                            IngredientsList = "Киноа 65 г, нут отварной 100 г, огурец 80 г, томаты 100 г, оливковое масло 10 г, лимонный сок 10 мл, соль 2 г, петрушка 5 г",
                            IsCustom = false,
                            IsForChildren = false,
                            MainIngredient = "Киноа",
                            Name = "Боул с киноа и нутом",
                            Proteins = 17m
                        },
                        new
                        {
                            Id = 18,
                            Calories = 480m,
                            Carbs = 50m,
                            CategoryId = 2,
                            CookingTime = 45,
                            Description = "1. Смешайте фарш индейки с рисом, яйцом и солью. 2. Сформируйте тефтели. 3. Тушите в томатном соусе до готовности.",
                            Fats = 14m,
                            ImageUrl = "/images/dishes/lunch.svg",
                            IngredientsList = "Фарш индейки 150 г, рис отварной 120 г, яйцо 0,5 шт., томатный соус 120 г, лук 35 г, растительное масло 5 г, соль 2 г",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Индейка",
                            Name = "Тефтели из индейки с рисом",
                            Proteins = 36m
                        },
                        new
                        {
                            Id = 19,
                            Calories = 410m,
                            Carbs = 36m,
                            CategoryId = 2,
                            CookingTime = 80,
                            Description = "1. Отварите говядину до мягкости. 2. Добавьте свеклу, капусту, картофель и морковь. 3. Варите до готовности и подавайте со сметаной.",
                            Fats = 17m,
                            ImageUrl = "/images/dishes/lunch.svg",
                            IngredientsList = "Говядина 120 г, свекла 100 г, капуста 90 г, картофель 100 г, морковь 50 г, лук 35 г, сметана 20 г, соль 2 г",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Говядина",
                            Name = "Борщ с говядиной",
                            Proteins = 28m
                        },
                        new
                        {
                            Id = 20,
                            Calories = 430m,
                            Carbs = 55m,
                            CategoryId = 2,
                            CookingTime = 25,
                            Description = "1. Отварите рис. 2. Быстро обжарьте креветки с овощами и соевым соусом. 3. Добавьте рис и прогрейте все вместе.",
                            Fats = 10m,
                            ImageUrl = "/images/dishes/lunch.svg",
                            IngredientsList = "Рис 70 г, креветки очищенные 140 г, зеленый горошек 50 г, морковь 50 г, соевый соус 10 мл, кунжутное масло 6 г, соль 1 г",
                            IsCustom = false,
                            IsForChildren = false,
                            MainIngredient = "Креветки",
                            Name = "Рис с креветками и овощами",
                            Proteins = 30m
                        },
                        new
                        {
                            Id = 21,
                            Calories = 360m,
                            Carbs = 12m,
                            CategoryId = 3,
                            CookingTime = 30,
                            Description = "1. Приправьте куриную грудку солью и специями. 2. Запеките вместе с брокколи и маслом. 3. Дайте мясу отдохнуть 5 минут перед подачей.",
                            Fats = 15m,
                            ImageUrl = "/images/dishes/dinner.svg",
                            IngredientsList = "Куриная грудка 170 г, брокколи 180 г, оливковое масло 10 г, соль 2 г, паприка 2 г, чеснок сушеный 1 г",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Курица",
                            Name = "Куриная грудка с брокколи",
                            Proteins = 42m
                        },
                        new
                        {
                            Id = 22,
                            Calories = 450m,
                            Carbs = 12m,
                            CategoryId = 3,
                            CookingTime = 40,
                            Description = "1. Обжарьте ломтики говядины на масле. 2. Добавьте цветную капусту и специи. 3. Тушите до мягкости мяса и овощей.",
                            Fats = 28m,
                            ImageUrl = "/images/dishes/dinner.svg",
                            IngredientsList = "Говядина 160 г, цветная капуста 200 г, сливочное масло 10 г, оливковое масло 5 г, соль 2 г, черный перец 1 г",
                            IsCustom = false,
                            IsForChildren = false,
                            MainIngredient = "Говядина",
                            Name = "Говядина с цветной капустой",
                            Proteins = 35m
                        },
                        new
                        {
                            Id = 23,
                            Calories = 380m,
                            Carbs = 11m,
                            CategoryId = 3,
                            CookingTime = 25,
                            Description = "1. Обжарьте кабачок, перец и шпинат. 2. Залейте яйцами с сыром. 3. Доведите до готовности на сковороде или в духовке.",
                            Fats = 27m,
                            ImageUrl = "/images/dishes/dinner.svg",
                            IngredientsList = "Яйца 3 шт., кабачок 80 г, болгарский перец 70 г, шпинат 40 г, сыр 30 г, оливковое масло 8 г, соль 2 г",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Яйца",
                            Name = "Фриттата с овощами",
                            Proteins = 24m
                        },
                        new
                        {
                            Id = 24,
                            Calories = 350m,
                            Carbs = 18m,
                            CategoryId = 3,
                            CookingTime = 20,
                            Description = "1. Нарежьте тофу и овощи. 2. Обжарьте их с имбирем и соевым соусом. 3. Посыпьте кунжутом и подавайте горячим.",
                            Fats = 20m,
                            ImageUrl = "/images/dishes/dinner.svg",
                            IngredientsList = "Тофу 180 г, брокколи 100 г, болгарский перец 80 г, соевый соус 15 мл, кунжутное масло 8 г, имбирь 5 г, кунжут 5 г",
                            IsCustom = false,
                            IsForChildren = false,
                            MainIngredient = "Тофу",
                            Name = "Тофу с овощами в соевом соусе",
                            Proteins = 22m
                        },
                        new
                        {
                            Id = 25,
                            Calories = 470m,
                            Carbs = 9m,
                            CategoryId = 3,
                            CookingTime = 30,
                            Description = "1. Измельчите лосось с яйцом и зеленью. 2. Сформируйте котлеты и обжарьте на масле. 3. Подайте с салатом из огурца и зелени.",
                            Fats = 31m,
                            ImageUrl = "/images/dishes/dinner.svg",
                            IngredientsList = "Филе лосося 160 г, яйцо 0,5 шт., огурец 100 г, листовой салат 50 г, оливковое масло 10 г, лимонный сок 8 мл, соль 2 г",
                            IsCustom = false,
                            IsForChildren = false,
                            MainIngredient = "Лосось",
                            Name = "Котлеты из лосося с салатом",
                            Proteins = 34m
                        },
                        new
                        {
                            Id = 26,
                            Calories = 330m,
                            Carbs = 54m,
                            CategoryId = 3,
                            CookingTime = 50,
                            Description = "1. Смешайте отварной рис с овощами и томатами. 2. Наполните перец начинкой. 3. Тушите в томатном соусе до мягкости.",
                            Fats = 9m,
                            ImageUrl = "/images/dishes/dinner.svg",
                            IngredientsList = "Болгарский перец 180 г, рис отварной 130 г, морковь 60 г, лук 40 г, томатный соус 120 г, растительное масло 7 г, соль 2 г",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Болгарский перец",
                            Name = "Перец, фаршированный овощами и рисом",
                            Proteins = 10m
                        },
                        new
                        {
                            Id = 27,
                            Calories = 390m,
                            Carbs = 24m,
                            CategoryId = 3,
                            CookingTime = 25,
                            Description = "1. Быстро обжарьте куриную печень с луком. 2. Добавьте яблоко и листья салата. 3. Заправьте маслом и бальзамическим уксусом.",
                            Fats = 20m,
                            ImageUrl = "/images/dishes/dinner.svg",
                            IngredientsList = "Куриная печень 160 г, яблоко 90 г, листовой салат 60 г, лук 35 г, оливковое масло 10 г, бальзамический уксус 8 мл, соль 2 г",
                            IsCustom = false,
                            IsForChildren = false,
                            MainIngredient = "Куриная печень",
                            Name = "Теплый салат с печенью и яблоком",
                            Proteins = 29m
                        },
                        new
                        {
                            Id = 28,
                            Calories = 220m,
                            Carbs = 24m,
                            CategoryId = 4,
                            CookingTime = 10,
                            Description = "1. Нарежьте морковь, огурец и перец брусочками. 2. Смешайте хумус с лимонным соком и паприкой. 3. Подавайте овощи с соусом.",
                            Fats = 11m,
                            ImageUrl = "/images/dishes/snack.svg",
                            IngredientsList = "Хумус 70 г, морковь 70 г, огурец 80 г, болгарский перец 80 г, лимонный сок 5 мл, паприка 1 г",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Хумус",
                            Name = "Овощные палочки с хумусом",
                            Proteins = 8m
                        },
                        new
                        {
                            Id = 29,
                            Calories = 210m,
                            Carbs = 27m,
                            CategoryId = 4,
                            CookingTime = 5,
                            Description = "1. Нарежьте яблоко дольками. 2. Смажьте арахисовой пастой. 3. Посыпьте корицей и подавайте сразу.",
                            Fats = 10m,
                            ImageUrl = "/images/dishes/snack.svg",
                            IngredientsList = "Яблоко 150 г, арахисовая паста 18 г, корица 1 г",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Яблоко",
                            Name = "Яблоко с арахисовой пастой",
                            Proteins = 5m
                        },
                        new
                        {
                            Id = 30,
                            Calories = 240m,
                            Carbs = 12m,
                            CategoryId = 4,
                            CookingTime = 5,
                            Description = "1. Смешайте творог с какао и йогуртом. 2. Добавьте подсластитель по вкусу. 3. Охладите 5 минут и подавайте.",
                            Fats = 8m,
                            ImageUrl = "/images/dishes/snack.svg",
                            IngredientsList = "Творог 2% 180 г, натуральный йогурт 40 г, какао 5 г, подсластитель 1 г, ванилин 1 г",
                            IsCustom = false,
                            IsForChildren = false,
                            MainIngredient = "Творог",
                            Name = "Протеиновый творог с какао",
                            Proteins = 30m
                        },
                        new
                        {
                            Id = 31,
                            Calories = 230m,
                            Carbs = 24m,
                            CategoryId = 4,
                            CookingTime = 7,
                            Description = "1. Разомните авокадо с лимонным соком и солью. 2. Намажьте массу на рисовые хлебцы. 3. Добавьте томаты и зелень.",
                            Fats = 14m,
                            ImageUrl = "/images/dishes/snack.svg",
                            IngredientsList = "Рисовые хлебцы 25 г, авокадо 80 г, томаты черри 60 г, лимонный сок 5 мл, соль 1 г, зелень 5 г",
                            IsCustom = false,
                            IsForChildren = false,
                            MainIngredient = "Авокадо",
                            Name = "Рисовые хлебцы с авокадо",
                            Proteins = 4m
                        },
                        new
                        {
                            Id = 32,
                            Calories = 260m,
                            Carbs = 42m,
                            CategoryId = 4,
                            CookingTime = 5,
                            Description = "1. Нарежьте банан. 2. Взбейте его с кефиром, ягодами и овсяными хлопьями. 3. Подавайте сразу после приготовления.",
                            Fats = 6m,
                            ImageUrl = "/images/dishes/snack.svg",
                            IngredientsList = "Кефир 1% 200 мл, банан 90 г, ягоды 60 г, овсяные хлопья 15 г, мед 5 г",
                            IsCustom = false,
                            IsForChildren = true,
                            MainIngredient = "Кефир",
                            Name = "Смузи с кефиром и бананом",
                            Proteins = 11m
                        });
                });

            modelBuilder.Entity("SmartMeal.Models.DishAllergen", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("AllergenId")
                        .HasColumnType("int");

                    b.HasKey("DishId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("DishAllergens");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            AllergenId = 1
                        },
                        new
                        {
                            DishId = 1,
                            AllergenId = 4
                        },
                        new
                        {
                            DishId = 2,
                            AllergenId = 1
                        },
                        new
                        {
                            DishId = 2,
                            AllergenId = 5
                        },
                        new
                        {
                            DishId = 2,
                            AllergenId = 4
                        },
                        new
                        {
                            DishId = 5,
                            AllergenId = 6
                        },
                        new
                        {
                            DishId = 5,
                            AllergenId = 3
                        },
                        new
                        {
                            DishId = 7,
                            AllergenId = 1
                        },
                        new
                        {
                            DishId = 7,
                            AllergenId = 4
                        },
                        new
                        {
                            DishId = 8,
                            AllergenId = 4
                        },
                        new
                        {
                            DishId = 8,
                            AllergenId = 1
                        },
                        new
                        {
                            DishId = 9,
                            AllergenId = 1
                        },
                        new
                        {
                            DishId = 9,
                            AllergenId = 5
                        },
                        new
                        {
                            DishId = 10,
                            AllergenId = 1
                        },
                        new
                        {
                            DishId = 10,
                            AllergenId = 2
                        },
                        new
                        {
                            DishId = 11,
                            AllergenId = 1
                        },
                        new
                        {
                            DishId = 11,
                            AllergenId = 5
                        },
                        new
                        {
                            DishId = 12,
                            AllergenId = 5
                        },
                        new
                        {
                            DishId = 12,
                            AllergenId = 3
                        },
                        new
                        {
                            DishId = 13,
                            AllergenId = 1
                        },
                        new
                        {
                            DishId = 14,
                            AllergenId = 4
                        },
                        new
                        {
                            DishId = 16,
                            AllergenId = 4
                        },
                        new
                        {
                            DishId = 16,
                            AllergenId = 6
                        },
                        new
                        {
                            DishId = 18,
                            AllergenId = 5
                        },
                        new
                        {
                            DishId = 19,
                            AllergenId = 1
                        },
                        new
                        {
                            DishId = 20,
                            AllergenId = 7
                        },
                        new
                        {
                            DishId = 20,
                            AllergenId = 8
                        },
                        new
                        {
                            DishId = 23,
                            AllergenId = 1
                        },
                        new
                        {
                            DishId = 23,
                            AllergenId = 5
                        },
                        new
                        {
                            DishId = 24,
                            AllergenId = 8
                        },
                        new
                        {
                            DishId = 25,
                            AllergenId = 5
                        },
                        new
                        {
                            DishId = 25,
                            AllergenId = 6
                        },
                        new
                        {
                            DishId = 25,
                            AllergenId = 3
                        },
                        new
                        {
                            DishId = 29,
                            AllergenId = 2
                        },
                        new
                        {
                            DishId = 30,
                            AllergenId = 1
                        },
                        new
                        {
                            DishId = 31,
                            AllergenId = 3
                        },
                        new
                        {
                            DishId = 32,
                            AllergenId = 1
                        },
                        new
                        {
                            DishId = 32,
                            AllergenId = 4
                        });
                });

            modelBuilder.Entity("SmartMeal.Models.DishDietType", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("DietTypeId")
                        .HasColumnType("int");

                    b.HasKey("DishId", "DietTypeId");

                    b.HasIndex("DietTypeId");

                    b.ToTable("DishDietTypes");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            DietTypeId = 5
                        },
                        new
                        {
                            DishId = 1,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 2,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 2,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 3,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 3,
                            DietTypeId = 5
                        },
                        new
                        {
                            DishId = 3,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 4,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 4,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 5,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 5,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 5,
                            DietTypeId = 5
                        },
                        new
                        {
                            DishId = 5,
                            DietTypeId = 6
                        },
                        new
                        {
                            DishId = 5,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 6,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 6,
                            DietTypeId = 3
                        },
                        new
                        {
                            DishId = 6,
                            DietTypeId = 5
                        },
                        new
                        {
                            DishId = 6,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 7,
                            DietTypeId = 5
                        },
                        new
                        {
                            DishId = 7,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 8,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 8,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 9,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 9,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 9,
                            DietTypeId = 3
                        },
                        new
                        {
                            DishId = 9,
                            DietTypeId = 4
                        },
                        new
                        {
                            DishId = 9,
                            DietTypeId = 6
                        },
                        new
                        {
                            DishId = 9,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 10,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 10,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 10,
                            DietTypeId = 3
                        },
                        new
                        {
                            DishId = 10,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 11,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 11,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 11,
                            DietTypeId = 3
                        },
                        new
                        {
                            DishId = 11,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 12,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 12,
                            DietTypeId = 3
                        },
                        new
                        {
                            DishId = 12,
                            DietTypeId = 4
                        },
                        new
                        {
                            DishId = 12,
                            DietTypeId = 6
                        },
                        new
                        {
                            DishId = 12,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 13,
                            DietTypeId = 3
                        },
                        new
                        {
                            DishId = 13,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 14,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 14,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 15,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 15,
                            DietTypeId = 3
                        },
                        new
                        {
                            DishId = 15,
                            DietTypeId = 5
                        },
                        new
                        {
                            DishId = 15,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 16,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 16,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 17,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 17,
                            DietTypeId = 3
                        },
                        new
                        {
                            DishId = 17,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 18,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 18,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 19,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 19,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 20,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 20,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 20,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 21,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 21,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 21,
                            DietTypeId = 5
                        },
                        new
                        {
                            DishId = 21,
                            DietTypeId = 6
                        },
                        new
                        {
                            DishId = 21,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 22,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 22,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 22,
                            DietTypeId = 4
                        },
                        new
                        {
                            DishId = 22,
                            DietTypeId = 6
                        },
                        new
                        {
                            DishId = 23,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 23,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 23,
                            DietTypeId = 3
                        },
                        new
                        {
                            DishId = 23,
                            DietTypeId = 4
                        },
                        new
                        {
                            DishId = 23,
                            DietTypeId = 6
                        },
                        new
                        {
                            DishId = 23,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 24,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 24,
                            DietTypeId = 3
                        },
                        new
                        {
                            DishId = 24,
                            DietTypeId = 5
                        },
                        new
                        {
                            DishId = 24,
                            DietTypeId = 6
                        },
                        new
                        {
                            DishId = 24,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 25,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 25,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 25,
                            DietTypeId = 4
                        },
                        new
                        {
                            DishId = 25,
                            DietTypeId = 6
                        },
                        new
                        {
                            DishId = 25,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 26,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 26,
                            DietTypeId = 3
                        },
                        new
                        {
                            DishId = 26,
                            DietTypeId = 5
                        },
                        new
                        {
                            DishId = 26,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 27,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 27,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 27,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 28,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 28,
                            DietTypeId = 3
                        },
                        new
                        {
                            DishId = 28,
                            DietTypeId = 5
                        },
                        new
                        {
                            DishId = 28,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 29,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 29,
                            DietTypeId = 3
                        },
                        new
                        {
                            DishId = 29,
                            DietTypeId = 5
                        },
                        new
                        {
                            DishId = 29,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 30,
                            DietTypeId = 1
                        },
                        new
                        {
                            DishId = 30,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 30,
                            DietTypeId = 3
                        },
                        new
                        {
                            DishId = 30,
                            DietTypeId = 5
                        },
                        new
                        {
                            DishId = 30,
                            DietTypeId = 6
                        },
                        new
                        {
                            DishId = 30,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 31,
                            DietTypeId = 2
                        },
                        new
                        {
                            DishId = 31,
                            DietTypeId = 3
                        },
                        new
                        {
                            DishId = 31,
                            DietTypeId = 5
                        },
                        new
                        {
                            DishId = 31,
                            DietTypeId = 7
                        },
                        new
                        {
                            DishId = 32,
                            DietTypeId = 5
                        },
                        new
                        {
                            DishId = 32,
                            DietTypeId = 7
                        });
                });

            modelBuilder.Entity("SmartMeal.Models.FavoriteDish", b =>
                {
                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.HasKey("UserProfileId", "DishId");

                    b.HasIndex("DishId");

                    b.ToTable("FavoriteDishes");
                });

            modelBuilder.Entity("SmartMeal.Models.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("SmartMeal.Models.UserAllergen", b =>
                {
                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int>("AllergenId")
                        .HasColumnType("int");

                    b.HasKey("UserProfileId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("UserAllergens");
                });

            modelBuilder.Entity("SmartMeal.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal>("DailyCalories")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Goal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Height")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityLevel = 3,
                            Age = 22,
                            DailyCalories = 2000m,
                            Email = "demo@smartmeal.local",
                            FullName = "Демо-пользователь",
                            Gender = "Женский",
                            Goal = "Поддержание веса",
                            Height = 170m,
                            Weight = 65m
                        });
                });

            modelBuilder.Entity("SmartMeal.Models.Dish", b =>
                {
                    b.HasOne("SmartMeal.Models.Category", "Category")
                        .WithMany("Dishes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Models.UserProfile", "CreatedByUserProfile")
                        .WithMany("CustomDishes")
                        .HasForeignKey("CreatedByUserProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("CreatedByUserProfile");
                });

            modelBuilder.Entity("SmartMeal.Models.DishAllergen", b =>
                {
                    b.HasOne("SmartMeal.Models.Allergen", "Allergen")
                        .WithMany("DishAllergens")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Models.Dish", "Dish")
                        .WithMany("DishAllergens")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("SmartMeal.Models.DishDietType", b =>
                {
                    b.HasOne("SmartMeal.Models.DietType", "DietType")
                        .WithMany("DishDietTypes")
                        .HasForeignKey("DietTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Models.Dish", "Dish")
                        .WithMany("DishDietTypes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietType");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("SmartMeal.Models.FavoriteDish", b =>
                {
                    b.HasOne("SmartMeal.Models.Dish", "Dish")
                        .WithMany("FavoriteDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Models.UserProfile", "UserProfile")
                        .WithMany("FavoriteDishes")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SmartMeal.Models.MealPlan", b =>
                {
                    b.HasOne("SmartMeal.Models.Dish", "Dish")
                        .WithMany("MealPlans")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Models.UserProfile", "UserProfile")
                        .WithMany("MealPlans")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SmartMeal.Models.UserAllergen", b =>
                {
                    b.HasOne("SmartMeal.Models.Allergen", "Allergen")
                        .WithMany("UserAllergens")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Models.UserProfile", "UserProfile")
                        .WithMany("UserAllergens")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SmartMeal.Models.Allergen", b =>
                {
                    b.Navigation("DishAllergens");

                    b.Navigation("UserAllergens");
                });

            modelBuilder.Entity("SmartMeal.Models.Category", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("SmartMeal.Models.DietType", b =>
                {
                    b.Navigation("DishDietTypes");
                });

            modelBuilder.Entity("SmartMeal.Models.Dish", b =>
                {
                    b.Navigation("DishAllergens");

                    b.Navigation("DishDietTypes");

                    b.Navigation("FavoriteDishes");

                    b.Navigation("MealPlans");
                });

            modelBuilder.Entity("SmartMeal.Models.UserProfile", b =>
                {
                    b.Navigation("CustomDishes");

                    b.Navigation("FavoriteDishes");

                    b.Navigation("MealPlans");

                    b.Navigation("UserAllergens");
                });
#pragma warning restore 612, 618
        }
    }
}
