// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartMeal.Data;

#nullable disable

namespace SmartMeal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260522215822_SeedReferenceData")]
    partial class SeedReferenceData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartMeal.Models.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Молочные продукты и лактоза.",
                            Name = "Молоко"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Орехи и продукты, которые могут содержать следы орехов.",
                            Name = "Орехи"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Апельсины, лимоны, мандарины и другие цитрусовые.",
                            Name = "Цитрусовые"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Пшеница, рожь, ячмень и продукты с глютеном.",
                            Name = "Глютен"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Куриные яйца и продукты с их содержанием.",
                            Name = "Яйца"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Рыба и рыбные продукты.",
                            Name = "Рыба"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Креветки, мидии, кальмары и другие морепродукты.",
                            Name = "Морепродукты"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Соя и соевые продукты.",
                            Name = "Соя"
                        });
                });

            modelBuilder.Entity("SmartMeal.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Завтрак",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Обед",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ужин",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Перекус",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("SmartMeal.Models.DietType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DietTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Рацион с повышенным содержанием белка.",
                            Name = "Высокобелковая"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Рацион без продуктов, содержащих глютен.",
                            Name = "Без глютена"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Рацион без мясных продуктов.",
                            Name = "Вегетарианская"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Рацион с низким содержанием углеводов и высоким содержанием жиров.",
                            Name = "Кето"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Рацион с пониженной калорийностью.",
                            Name = "Низкокалорийная"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Рацион с ограничением углеводов.",
                            Name = "Низкоуглеводная"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Сбалансированный рацион для здорового питания.",
                            Name = "Правильное питание"
                        });
                });

            modelBuilder.Entity("SmartMeal.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Calories")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Carbs")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CookingTime")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByUserProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fats")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("IngredientsList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForChildren")
                        .HasColumnType("bit");

                    b.Property<string>("MainIngredient")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Proteins")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserProfileId");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("SmartMeal.Models.DishAllergen", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("AllergenId")
                        .HasColumnType("int");

                    b.HasKey("DishId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("DishAllergens");
                });

            modelBuilder.Entity("SmartMeal.Models.DishDietType", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("DietTypeId")
                        .HasColumnType("int");

                    b.HasKey("DishId", "DietTypeId");

                    b.HasIndex("DietTypeId");

                    b.ToTable("DishDietTypes");
                });

            modelBuilder.Entity("SmartMeal.Models.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("SmartMeal.Models.UserAllergen", b =>
                {
                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int>("AllergenId")
                        .HasColumnType("int");

                    b.HasKey("UserProfileId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("UserAllergens");
                });

            modelBuilder.Entity("SmartMeal.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal>("DailyCalories")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Goal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Height")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("SmartMeal.Models.Dish", b =>
                {
                    b.HasOne("SmartMeal.Models.Category", "Category")
                        .WithMany("Dishes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Models.UserProfile", "CreatedByUserProfile")
                        .WithMany("CustomDishes")
                        .HasForeignKey("CreatedByUserProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("CreatedByUserProfile");
                });

            modelBuilder.Entity("SmartMeal.Models.DishAllergen", b =>
                {
                    b.HasOne("SmartMeal.Models.Allergen", "Allergen")
                        .WithMany("DishAllergens")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Models.Dish", "Dish")
                        .WithMany("DishAllergens")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("SmartMeal.Models.DishDietType", b =>
                {
                    b.HasOne("SmartMeal.Models.DietType", "DietType")
                        .WithMany("DishDietTypes")
                        .HasForeignKey("DietTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Models.Dish", "Dish")
                        .WithMany("DishDietTypes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietType");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("SmartMeal.Models.MealPlan", b =>
                {
                    b.HasOne("SmartMeal.Models.Dish", "Dish")
                        .WithMany("MealPlans")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Models.UserProfile", "UserProfile")
                        .WithMany("MealPlans")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SmartMeal.Models.UserAllergen", b =>
                {
                    b.HasOne("SmartMeal.Models.Allergen", "Allergen")
                        .WithMany("UserAllergens")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Models.UserProfile", "UserProfile")
                        .WithMany("UserAllergens")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SmartMeal.Models.Allergen", b =>
                {
                    b.Navigation("DishAllergens");

                    b.Navigation("UserAllergens");
                });

            modelBuilder.Entity("SmartMeal.Models.Category", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("SmartMeal.Models.DietType", b =>
                {
                    b.Navigation("DishDietTypes");
                });

            modelBuilder.Entity("SmartMeal.Models.Dish", b =>
                {
                    b.Navigation("DishAllergens");

                    b.Navigation("DishDietTypes");

                    b.Navigation("MealPlans");
                });

            modelBuilder.Entity("SmartMeal.Models.UserProfile", b =>
                {
                    b.Navigation("CustomDishes");

                    b.Navigation("MealPlans");

                    b.Navigation("UserAllergens");
                });
#pragma warning restore 612, 618
        }
    }
}
